config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'gears#index'
  resources :gears do
    resources :reviews
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :gears
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  belongs_to :maker
  belongs_to :club
  has_many :reviews

end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :gears
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :gear
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gears
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :find_gear, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :edit]
  def index
    @users = User.all.order("created_at DESC")
    if params[:maker].blank?
      @gears = Gear.all.
      order("created_at DESC")
    else
      @maker_id = Maker.find_by(name: params[:maker]).id
      @gears = Gear.where(maker_id: @maker_id).order("created_at DESC")
    end
  end

  def show
    if @gear.reviews.blank?
      @average_review = 0
    else
      @average_review = @gear.reviews.average(:rating).round(2)
    end
  end

  def new
    @gear = current_user.gears.new
  end
  
  def create
    @gear = current_user.gears.new(gear_params)
    if @gear.save
      redirect_to root_path, notice: 'Gear was successfully created.'
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @gear.update(gear_params)
      redirect_to gear_path(@gear), notice: 'Gear was successfully updated.'
    else
      render 'edit'
    end
  end
  
  def destroy
    @gear.destroy
    redirect_to root_path, notice: 'Gear was successfully destroyed.'
  end

  private
    def gear_params
      params.require(:gear).permit(:name, :description, :maker_id, :club_id, :image)
    end

    def find_gear
      @gear = Gear.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_gear
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @review.gear_id = @gear.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to gear_path(@gear), notice: 'Review was successfully created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @review.destroy
    redirect_to gear_path(@gear), notice: 'Review was successfully deleted.'
  end
  
  def update
    if @review.update(review_params)
      redirect_to gear_path(@gear), notice: 'Review was successfully updated.'
    else
      render 'edit'
    end
  end



  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_gear
      @gear = Gear.find(params[:gear_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  
  def show
    @gears = @user.gears.includes(:maker)
    @drivers = @gears.where(club_id: 1)
    @fairwaywoods = @gears.where(club_id: 2)
    @utilitys = @gears.where(club_id: 3)
    @irons = @gears.where(club_id: 4)
    @wedges = @gears.where(club_id: 5)
    @putters = @gears.where(club_id: 6)
    @balls = @gears.where(club_id: 7)
  end

  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gears/_form.html.erb
  <%= form_with(model: @gear, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name, "Gear Name" %>
      <%= form.text_field :name, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= form.label :maker_id, "Maker" %>
      <%= form.select(:maker_id, Maker.all.map {|maker|[maker.name, maker.id] }, {prompt: "Select Maker"}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <%= form.label :club_id, "Club"  %>
      <%= form.select(:club_id, Club.all.map {|club|[club.name, club.id] }, {prompt: "Club or Accesory"}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <%= form.label :image, "Photo" %>
      <%= form.file_field :image, {class: "filestyle"} %>
    </div>
      <%= form.submit "Post", {class: "btn-custom2"} %>
    
  <% end %>

app/views/gears/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  
  <div class="new-gear-form">

    <div class="form-group">
      <h1>Edit Gear</h1>


      <%= form_with(model:@gear, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :name, "Gear Name" %>
          <%= form.text_field :name, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= form.label :description, "Description" %>
          <%= form.text_area :description, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= form.label :maker_id, "Maker" %>
          <%= form.select(:maker_id, Maker.all.map {|maker|[maker.name, maker.id] }, {prompt: "Select Maker"}, {class: "form-control"}) %>
        </div>
        <div class="form-group">
          <%= form.label :club_id, "Club"  %>
          <%= form.select(:club_id, Club.all.map {|club|[club.name, club.id] }, {prompt: "Club or Accesory"}, {class: "form-control"}) %>
        </div>
        <div class="form-group">
          <%= form.label :image, "Photo" %>
          <%= form.file_field :image, {class: "filestyle"} %>
        </div>
          <%= form.submit "Post", {class: "btn-custom2"} %>
      <% end %>
    </div>
  </div>
</div>

app/views/gears/index.html.erb
<div class="row">
  <h1 class="title">PLAYERS</h1>
    <% @users.each do |user| %>
      <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
        <%= link_to (image_tag user.image.url, class: "icon_image"), user %>
      </div>
    <% end %>
</div>


<div class="row">
  <h1 class="title"><%= params[:maker] %></h1>
    <% if @gears.count == 0 %>
      <h2>No Gear</h2>
    <% else %>
      <h1 class="title">GEARS</h1>
        <% @gears.each do |gear| %>
          <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
            <%= link_to (image_tag gear.image.url, class: "gear"), gear %>
          </div>
        <% end %>
    <% end %>
</div>

app/views/gears/new.html.erb
<div class="col-md-6 col-md-offset-3">
  
  <div class="new-gear-form">
  
    <h1>New Gear</h1>
  
    <%= render 'form' %>
  
  </div>

</div>

app/views/gears/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="showpage-top">
      <div class="col-sm-12 col-md-4">      
        <%= image_tag @gear.image.url, class: "gear-image" %>
      </div>
      <div class="col-sm-12 col-md-8">
        <div class="gear-info">
          <h2 class="gear-title"><%= @gear.name %></h2>
          <h3 class="gear-maker"><%= @gear.maker.name %></h3>
          <h4 class="gear-club"><%= @gear.club.name %></h4>
          <div class="gear-desc"><%= @gear.description %></div>
          <div class="avg-rating">
            <p>Average Rating</p>
            <div class="average-review-rating" data-score=<%= @average_review %>></div>
            <span class="number-of-reviews">Based on <%= @gear.reviews.count %> Reviews</span>
          </div>
          <div class="links btn-group">
            <%= link_to "Back", root_path, class: "btn btn-custom" %>
            <% if user_signed_in? && @gear.user_id == current_user.id %>
              <%= link_to "Edit", edit_gear_path(@gear), class: "btn btn-custom" %>
              <%= link_to "Delete", gear_path(@gear), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <% if @gear.reviews.empty? %>
        <h4>Not Reviewed Yet</h4>
      <% else %>
        <h1>Reviews</h1>
        <%= render @gear.reviews %>
      <% end %>
      <%= render partial: 'reviews/form', locals: {gear: @gear} %>
    </div>
  </div>
</div>




<script>
  $('.review-rating').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>
<script>
  $('.average-review-rating').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfGearReview</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('theplayers.ico') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.raty.js', "data-turbolinks-track" => false %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Gear Review", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, user_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Maker<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Maker.all.each do |maker| %>
                <li class="<%= 'active' if params[:maker] == maker.name %>">
                  <%= link_to maker.name, gears_path(maker: maker.name), class: "link" %>
                </li>
              <% end %>    
            </ul>
          </li>

          <% if user_signed_in? %>
            <li><%= link_to "Add Gear", new_gear_path %></li>
          <% end %>
        
        </ul>

      </div>
    </nav>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-warning") %>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
    
  
  </body>
</html>

app/views/reviews/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: [@gear, @gear.reviews.new], local: true) do |f| %>
    <div id="rating-form">
      <label>Rating</label>
    </div>
    <div class="form-group">
      <%= f.label :comment, "Comment" %>
      <%= f.text_area :comment, {class: "form-control"} %>
    </div>
      <%= f.button :post, {class: "btn-custom2"} %>
    <% end %>
  <% end %>


<script>
  $('#rating-form').raty({
    // path: '/assets/',
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-content">
      <div class="review-rating" data-score="<%= review.rating %>"></div>
      <p><%= review.comment %></p>
  </div>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
    <div class="links btn-group">
      <%= link_to "Edit", edit_gear_review_path(review.gear, review), class: "btn btn-custom" %>
      <%= link_to "Delete", gear_review_path(review.gear, review), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom" %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@gear, @review]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="profile">
    <% if user_signed_in? && @user.id == current_user.id %>
      <% if @user.image.blank? %>
        <%= link_to (image_tag 'theplayers.png', class: "icon_image"), edit_user_registration_path(@user) %> 
      <% else %>
        <%= link_to (image_tag @user.image.url, class: "icon_image"), edit_user_registration_path(@user) %> 
      <% end %>
    <% else %>
      <% if @user.image.blank? %>
        <%= image_tag 'theplayers.png', class: "icon_image" %>
      <% else %>
        <%= image_tag @user.image.url, class: "icon_image" %>
      <% end %>
    <% end %>

    <% if user_signed_in? && @user.id == current_user.id %>
      <h1><%= link_to @user.name, edit_user_registration_path(@user), class: "player-name" %></h1>
    <% else %>
      <div class="player-name"><h1><%= @user.name %></h1></div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Driver</h1>
      <% if @drivers.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @drivers.each do |driver| %>
          <%= link_to(gear_path(driver), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag driver.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= driver.name %></h2>
                <h3><%= driver.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>FairwayWood</h1>
      <% if @fairwaywoods.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @fairwaywoods.each do |fairwaywood| %>
          <%= link_to(gear_path(fairwaywood), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag fairwaywood.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= fairwaywood.name %></h2>
                <h3><%= fairwaywood.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Utility</h1>
      <% if @utilitys.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @utilitys.each do |utility| %>
          <%= link_to(gear_path(utility), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag utility.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= utility.name %></h2>
                <h3><%= utility.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Iron</h1>
      <% if @irons.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @irons.each do |iron| %>
          <%= link_to(gear_path(iron), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag iron.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= iron.name %></h2>
                <h3><%= iron.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Wedge</h1>
      <% if @wedges.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @wedges.each do |wedge| %>
          <%= link_to(gear_path(wedge), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag wedge.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= wedge.name %></h2>
                <h3><%= wedge.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Putter</h1>
      <% if @putters.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @putters.each do |putter| %>
          <%= link_to(gear_path(putter), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag putter.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= putter.name %></h2>
                <h3><%= putter.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="club">
    <h1>Ball</h1>
      <% if @balls.empty? %>
        <div class="club-card-empty"><h2>No Club</h2></div>
      <% else %>
        <% @balls.each do |ball| %>
          <%= link_to(gear_path(ball), class: "club-card-link") do %>
            <div class="club-card">
              <%= image_tag ball.image.url, class: "gear" %>
              <div class="club-card-desc">
                <h2><%= ball.name %></h2>
                <h3><%= ball.maker.name %></h3>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>